Repository Let-s-Jam/letsjamFE, pull requests merged in 2022-10, with the labels that each got.

#12 Feature/header
  src/app/app.component.html
  src/app/app.module.ts
  src/app/header/header.component.css
  src/app/header/header.component.html
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/jammer-profile/jammer-profile.component.css
  src/app/jammer-profile/jammer-profile.component.html
  src/app/jammer-profile/jammer-profile.component.spec.ts
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/results-page/results-page.component.css
  src/app/results-page/results-page.component.html
  src/app/results-page/results-page.component.spec.ts
  src/app/results-page/results-page.component.ts
  src/app/searchbar/searchbar.component.css
  src/app/searchbar/searchbar.component.html
  src/app/searchbar/searchbar.component.spec.ts
  src/app/searchbar/searchbar.component.ts
  src/assets/chat.png
  src/assets/guitar.png
  src/assets/laptop.png
  src/assets/listening.png
  src/assets/music.png
  src/assets/panda.png
  src/index.html
Labels: enhancement

#15 Add user profile components and jam request components and basic architecture
  src/app/accepted-jammers/accepted-jammers.component.css
  src/app/accepted-jammers/accepted-jammers.component.html
  src/app/accepted-jammers/accepted-jammers.component.spec.ts
  src/app/accepted-jammers/accepted-jammers.component.ts
  src/app/app.module.ts
  src/app/jam-requests/jam-requests.component.css
  src/app/jam-requests/jam-requests.component.html
  src/app/jam-requests/jam-requests.component.spec.ts
  src/app/jam-requests/jam-requests.component.ts
  src/app/user-profile/user-profile.component.css
  src/app/user-profile/user-profile.component.html
  src/app/user-profile/user-profile.component.spec.ts
  src/app/user-profile/user-profile.component.ts
Labels: enhancement

#17 Add home button
  src/app/header/header.component.html
Labels: enhancement

#18 Feature/profile page
  src/app/user-profile/user-profile.component.html
  src/app/user-profile/user-profile.component.ts
Labels: enhancement

#19 Add dummy test file and imports for local testing before using dummy server
  src/app/jammer-profile/jammer-profile.component.html
  src/app/jammer-profile/jammer-profile.component.ts
  src/dummy-data.ts
Labels: enhancement

#20 Dynamically render other user data to search results page
  src/app/jammer-profile/jammer-profile.component.html
  src/app/jammer-profile/jammer-profile.component.ts
Labels: enhancement

#21 Add user service and injectable for retrieving search data from mock API
  src/app/app.module.ts
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/services/user-service.ts
Labels: enhancement

#22 Fix JSON shape, remove type text from getJammers method to complete functionality
  src/app/services/user-service.ts
Labels: enhancement

#23 Add getUserProfile method to userService, add subscription to ngOnInit in user profile component
  src/app/services/user-service.ts
  src/app/user-profile/user-profile.component.ts
Labels: enhancement

#24 Add UserService provider to user profile component, make user profile dynamically display user data
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/services/user-service.ts
  src/app/user-profile/user-profile.component.html
  src/app/user-profile/user-profile.component.ts
Labels: enhancement

#25 Refactor paths, add dynamic user info and pictures to incoming requests section
  src/app/jam-requests/jam-requests.component.html
  src/app/jam-requests/jam-requests.component.ts
  src/app/jammer-profile/jammer-profile.component.html
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/services/user-service.ts
  src/app/user-profile/user-profile.component.ts
Labels: enhancement

#26 Add more styling to the page, add scroll bar, add flex box several components
  src/app/accepted-jammers/accepted-jammers.component.css
  src/app/header/header.component.css
  src/app/jam-requests/jam-requests.component.css
  src/app/jammer-profile/jammer-profile.component.css
  src/app/jammer-profile/jammer-profile.component.html
  src/app/user-profile/user-profile.component.css
Labels: enhancement

#27 Add subscription for friends list, make friends list display dynamic data, add genres category
  src/app/accepted-jammers/accepted-jammers.component.html
  src/app/accepted-jammers/accepted-jammers.component.ts
  src/app/services/user-service.ts
Labels: enhancement

#28 Feature/edit profile
  src/app/app.module.ts
  src/app/user-info/user-info.component.css
  src/app/user-info/user-info.component.html
  src/app/user-info/user-info.component.spec.ts
  src/app/user-info/user-info.component.ts
  src/app/user-profile/user-profile.component.html
  src/app/user-profile/user-profile.component.spec.ts
Labels: enhancement

#29 Feature/edit profile2
  src/app/app.module.ts
  src/app/user-edit/user-edit.component.css
  src/app/user-edit/user-edit.component.html
  src/app/user-edit/user-edit.component.spec.ts
  src/app/user-edit/user-edit.component.ts
  src/app/user-info/user-info.component.html
  src/app/user-info/user-info.component.ts
  src/app/user-profile/user-profile.component.html
  src/app/user-profile/user-profile.component.ts
Labels: bug

#30 Fix bug that allows the edit profile form to show and toggle between …
  src/app/user-edit/user-edit.component.html
  src/app/user-edit/user-edit.component.ts
  src/app/user-info/user-info.component.html
  src/app/user-info/user-info.component.ts
  src/app/user-profile/user-profile.component.html
  src/app/user-profile/user-profile.component.ts
Labels: enhancement

#31 Feature/edit profile post
  src/app/services/user-service.ts
  src/app/user-edit/user-edit.component.html
  src/app/user-edit/user-edit.component.ts
  src/app/user-info/user-info.component.html
  src/app/user-info/user-info.component.ts
  tsconfig.app.json
Labels: bug

#33 Added divs and flexbox to rearrange user-profile page
  src/app/jam-requests/jam-requests.component.css
  src/app/jam-requests/jam-requests.component.html
  src/app/user-edit/user-edit.component.css
  src/app/user-info/user-info.component.css
  src/app/user-profile/user-profile.component.css
  src/app/user-profile/user-profile.component.html
Labels: enhancement

#35 Feature/user patch
  angular.json
  package.json
  proxy.conf.json
  src/app/accepted-jammers/accepted-jammers.component.ts
  src/app/jam-requests/jam-requests.component.ts
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/services/user-service.ts
  src/app/user-edit/user-edit.component.html
  src/app/user-edit/user-edit.component.ts
  src/app/user-info/user-info.component.html
  src/app/user-info/user-info.component.ts
  src/app/user-profile/user-profile.component.ts
Labels: enhancement

#36 Update endpoints for getting friends and pending friends
  src/app/accepted-jammers/accepted-jammers.component.ts
  src/app/jam-requests/jam-requests.component.ts
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/services/user-service.ts
Labels: bug

#37 Feature/type errors
  src/app/accepted-jammers/accepted-jammers.component.html
  src/app/accepted-jammers/accepted-jammers.component.ts
  src/app/user-profile/user-profile.component.ts
Labels: enhancement

#38 Feature/ts interfaces
  src/app/jam-requests/jam-requests.component.html
  src/app/jam-requests/jam-requests.component.ts
  src/app/jammer-profile/jammer-profile.component.html
  src/app/jammer-profile/jammer-profile.component.ts
Labels: enhancement

#40 Give PATCH request defined body and options, update function
  src/app/services/user-service.ts
  src/app/user-edit/user-edit.component.html
  src/app/user-edit/user-edit.component.ts
Labels: bug

#43 Add emitter for the search form, refactor other components to accommodate
  package-lock.json
  package.json
  src/app/jammer-profile/jammer-profile.component.css
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/results-page/results-page.component.html
  src/app/results-page/results-page.component.ts
  src/app/searchbar/searchbar.component.html
  src/app/searchbar/searchbar.component.ts
  src/app/user-profile/user-profile.component.css
  src/styles.css
Labels: enhancement

#44 Add logic to handle adding search terms to URI
  src/app/searchbar/searchbar.component.html
  src/app/searchbar/searchbar.component.ts
Labels: enhancement

#45 Feature/search function
  src/app/searchbar/searchbar.component.ts
  src/app/services/user-service.ts
Labels: enhancement

#46 Add observable for sendJammerSearchParams
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/results-page/results-page.component.html
  src/app/results-page/results-page.component.ts
  src/app/searchbar/searchbar.component.ts
  src/app/services/user-service.ts
Labels: enhancement

#47 Fix userService, add loops to iterate over data structure, refactor services
  src/app/jammer-profile/jammer-profile.component.html
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/searchbar/searchbar.component.ts
  src/app/services/user-service.ts
Labels: enhancement

#48 Change zipcode and distance in the components bringing in that data
  src/app/accepted-jammers/accepted-jammers.component.html
  src/app/jam-requests/jam-requests.component.html
  src/app/jammer-profile/jammer-profile.component.html
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/searchbar/searchbar.component.html
  src/app/services/user-service.ts
Labels: enhancement

#50 Add patch to accept jam requests, add function to call patch on click
  src/app/jam-requests/jam-requests.component.html
  src/app/jam-requests/jam-requests.component.ts
  src/app/services/user-service.ts
Labels: enhancement

#54 Github did not show us the full extent of the merge conflict, incredible stuff
  src/app/jam-requests/jam-requests.component.ts
Labels: enhancement

#55 Make http requests into https requests
  src/app/services/user-service.ts
Labels: enhancement

#56 Add httpclientmodule imports to all test spec files, add skeletons for additional tests
  src/app/accepted-jammers/accepted-jammers.component.spec.ts
  src/app/header/header.component.spec.ts
  src/app/jam-requests/jam-requests.component.spec.ts
  src/app/jammer-profile/jammer-profile.component.spec.ts
  src/app/results-page/results-page.component.spec.ts
  src/app/searchbar/searchbar.component.spec.ts
  src/app/services/user-services.spec.ts
  src/app/user-edit/user-edit.component.spec.ts
  src/app/user-info/user-info.component.spec.ts
  src/app/user-profile/user-profile.component.spec.ts
Labels: help wanted

#57 remove console logs and code comments, fix bug affecting users displaying to friends section
  src/app/accepted-jammers/accepted-jammers.component.html
  src/app/accepted-jammers/accepted-jammers.component.ts
  src/app/app.module.ts
  src/app/jam-requests/jam-requests.component.ts
  src/app/jammer-profile/jammer-profile.component.css
  src/app/jammer-profile/jammer-profile.component.html
  src/app/jammer-profile/jammer-profile.component.ts
  src/app/results-page/results-page.component.html
  src/app/results-page/results-page.component.ts
  src/app/searchbar/searchbar.component.ts
  src/app/services/user-service.ts
  src/app/services/user-services.spec.ts
  src/app/user-edit/user-edit.component.ts
  src/app/user-info/user-info.component.ts
  src/app/user-profile/user-profile.component.html
  src/app/user-profile/user-profile.component.ts
Labels: enhancement

#58 Change http to https for 1 url
  src/app/services/user-service.ts
Labels: enhancement
